apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-podinfo
  namespace: argocd
spec:
  description: Project for podinfo team
  sourceRepos:
    - https://github.com/VA-LEKSEEVA/AgroCD-GitOps.git
    - https://stefanprodan.github.io/podinfo
  destinations:
    - namespace: 'podinfo-*'        # разрешены только неймспейсы с префиксом podinfo-
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace               # разрешаем создавать только Namespace из cluster‑level ресурсов
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'                     # любые namespaced ресурсы разрешены
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota           # запрещаем ResourceQuota
    - group: ''
      kind: LimitRange              # запрещаем LimitRange
