apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-podinfo
  namespace: argocd
spec:
  description: Project for podinfo applications
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'podinfo-*'
      server: https://kubernetes.default.svc
    - namespace: 'argocd'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
