replicaCount: 1
ui:
  color: "#ff6b6b"
  message: "DEV via ArgoCD - UPDATED"
resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 32Mi

extraEnvs:
  - name: OTEL_SERVICE_NAME
    value: "podinfo-dev"
  - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
    value: "http://tempo.monitoring.svc.cluster.local:4317"
