apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: podinfo
  namespace: podinfo-dev
  labels:
    release: kps
spec:
  selector:
    matchLabels:
      app: podinfo        # метка deployment podinfo (проверьте, что у service такие же)
  endpoints:
    - port: 9898
      path: /metrics
      interval: 15s
