fullnameOverride: kps

prometheus:
  prometheusSpec:
    retention: 15d
    retentionSize: 5GB
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        memory: 512Mi
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi   # уменьшили с 10Gi

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 20m
        memory: 32Mi
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'severity']
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 1h
      receiver: 'null'
    receivers:
      - name: 'null'
    inhibit_rules:
      - source_matchers: [severity="critical"]
        target_matchers: [severity="warning"]
        equal: [alertname, namespace]

grafana:
  adminPassword: "admin"
  service:
    type: ClusterIP
  persistence:
    enabled: true
    size: 2Gi   # уменьшили с 5Gi
  defaultDashboardsTimezone: browser
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

nodeExporter:
  enabled: true

kube-state-metrics:
  enabled: true
